Add global grid width, height and thickness settings
krzys-h/UndertaleModTool pull request #1005
Opened 2022-06-26 09:01 UTC by Miepee

## Description
This PR adds global room grid width, height and thickness settings, which override the automatically calculated grid width / height and hardcoded grid thickness.

### Caveats
None

### Notes
This is Change 2 of #931.

2022-06-26 13:04 UTC, VladiStep commented
The room grid settings should be separated, as it done with a profile mode settings.
Also, the settings labels are not centered with the text boxes.

2022-06-26 18:04 UTC, Miepee commented
Addressed those

2022-06-26 20:35 UTC, VladiStep commented
You didn't properly aligned the check boxes and their labels - you should add `VerticalAlignment="Center"` to each checkbox and label.

2022-06-27 10:19 UTC, VladiStep requested changes

2022-06-27 10:19 UTC, VladiStep commented on UndertaleModTool/Windows/SettingsWindow.xaml
> +            <CheckBox Grid.Row="5" Grid.Column="2" Margin="3"  Content="" IsChecked="{Binding UseGMLCache}"/>
You forgot to remove redundant spaces.

2022-06-27 10:19 UTC, VladiStep commented on UndertaleModTool/Controls/UndertaleRoomRenderer.xaml.cs
>              UndertaleRoomEditor.GenerateSpriteCache(DataContext as UndertaleRoom);
```suggestion
            if (DataContext is not UndertaleRoom room)
                return;
            
            UndertaleRoomEditor.SetupRoomWithGrids(room);
            UndertaleRoomEditor.GenerateSpriteCache(room);
```

2022-06-27 13:05 UTC, VladiStep commented on UndertaleModLib/Models/UndertaleRoom.cs
> +        if (tileSizes.Count <= 0) return;
Add default size assignment (`16`) besides `return`.

2022-06-27 13:34 UTC, VladiStep commented on UndertaleModLib/Models/UndertaleRoom.cs
> +        // If tiles exist at all, grab the most used tile size and use that as our grid size
Move this comment right before line 424.

2022-06-27 13:46 UTC, VladiStep approved these changes

2022-06-27 15:47 UTC, merged