Fixes and Improvements to NewTextureRepacker.
krzys-h/UndertaleModTool pull request #1376
Opened 2023-05-08 12:58 UTC by JohnnyonFlame

## Description
This series fixes a long standing bug that was present on NewTextureRepacker, which caused subpar bin packing, and also adds the ability to change the bin sizes on both dimensions.

### Caveats
n/a

### Notes
n/a

2023-09-13 11:38 UTC, VladiStep requested changes

2023-09-13 11:38 UTC, VladiStep commented on UndertaleModTool/Scripts/Resource Repackers/NewTextureRepacker.csx
> +List<TextureAtlas> layoutPageItemList(List<TPageItem> items, int pageSizeWidth, int pageSizeHeght, int padding)
```suggestion
List<TextureAtlas> layoutPageItemList(List<TPageItem> items, int pageSizeWidth, int pageSizeHeight, int padding)
```

2023-09-13 11:38 UTC, VladiStep commented on UndertaleModTool/Scripts/Resource Repackers/NewTextureRepacker.csx
> +        var atlas = new TextureAtlas(pageSizeWidth, pageSizeHeght, padding);
```suggestion
        var atlas = new TextureAtlas(pageSizeWidth, pageSizeHeight, padding);
```

2023-09-13 11:39 UTC, VladiStep commented
There was a typo ("pageSizeHe**i**ght").

2023-10-02 03:09 UTC, JohnnyonFlame commented
Sorry forgot to push the fixes.

2023-10-31 04:20 UTC, merged