Major Profile Mode improvements
krzys-h/UndertaleModTool pull request #1443
Opened 2023-07-21 15:50 UTC by Romualdo666

## Description
When opening a data.win, all the code in the Temp Profile folder is replaced with the main, and when saving, all the main is replaced with the temp. this, to avoid wrong overwriting. Also, exporting profiles will actually overwrite the already exported profiles, and importing too. Fixed the issue where Importing Profiles wouldn't edit the dissasembly code.
### Caveats
If you had a tab with code opened, and you import THAT code with the "Import Profile" button, it will get overwritten, but visually won't be updated until you close or switch the tab.

### Notes
Sorry if I'm making too many pull request, haha.

2023-09-13 11:56 UTC, VladiStep commented
Your PR also has the old "dogcheck" and some compiler changes that you didn't mention.
You should make separate PRs for them.

2023-10-31 04:16 UTC, colinator27 commented
> Your PR also has the old "dogcheck" and some compiler changes that you didn't mention. You should make separate PRs for them.

Agreed on this -- currently we have no intention of restoring the "dogcheck" mechanism that confused many people. Also, seems like there's some extraneous compiler changes, as well as some code that maybe should be locked behind a profile mode check (e.g., checking for string comments).

2023-11-27 16:34 UTC, Miepee commented
@Romualdo666 could you please revert the dogcheck?

2023-11-27 22:24 UTC, Romualdo666 commented
aight sure

2023-11-27 22:31 UTC, Romualdo666 commented
@Miepee that should do it

2023-11-27 22:37 UTC, Miepee requested changes

2023-11-27 22:37 UTC, Miepee commented on UndertaleModTool/Resources/mus_dance_of_dog.wav
this iss till dogcheck related

2023-11-27 22:37 UTC, Miepee commented on UndertaleModTool/Resources/spr_tobdogl/0.png
this is still dogcheck related

2023-11-27 22:37 UTC, Miepee commented on UndertaleModTool/Resources/spr_tobdogl/1.png
this is still dogcheck related

2023-11-27 22:37 UTC, Miepee commented on UndertaleModTool/UndertaleModTool.csproj
> +	</ItemGroup>
this is still dogcheck related

2023-11-27 22:37 UTC, Miepee commented on UndertaleModTool/Windows/SettingsWindow.xaml
why is this deleted?

2023-11-27 22:37 UTC, Miepee commented on UndertaleModTool/MainWindow.xaml
> +                                                <BitmapImage UriSource="Resources/spr_tobdogl/0.png"/>
this is still dogcheck related

2023-11-27 22:38 UTC, Romualdo666 commented
oh crap i deleted the wrong file my bad. also, didnt know the assets were also needed to get deleted. i'll delete them then.

2023-11-27 22:54 UTC, closed without merging

2023-11-27 22:54 UTC, Romualdo666 commented
@Miepee this was already a mess so i am just making a new pull request when i have it done, sorry.